### PR TITLE
Update redoc, and optimize dockerfile

### PR DESCRIPTION
**Pull request by thaJeztah**
Update ReDoc to 1.14.0, and optimize the Dockerfile;

- Switch to nginx:alpine
- Use COPY instead of ADD
- Add a docker ignore file to prevent `.git` and other files to be added to the image

ping @bfirsh PTAL ❤️

### CODE REVIEW

**Comment by bfirsh** [comment]
Thanks!

In theory this should build a new image. If that doesn't work ping me and I'll give the build a kick. :)

**Comment by thaJeztah** [comment]
Thanks! I'll have a look, I started doing this because there was an issue reported for the docs, which I hoped would be resolved in the new version of ReDoc, but it didn't fix the issue. Thought it would still be good to open a PR :smile:

**Comment by thaJeztah** [comment]
Looks like it built a new image, but only tagged `:latest`, so possibly needs some changes to the auto build settings (https://hub.docker.com/r/bfirsh/redoc/tags/)

**Comment by thaJeztah** [comment]
Oh, probably has to be tagged :)

**Comment by bfirsh** [comment]
@thaJeztah Ah - yes. Tagged, so hopefully that'll build now. :)

**Comment by thaJeztah** [comment]
Yes! That seemed to have done the job, thanks!

**Pull request merged**
